# Basic workflow
name: build

# Controls when the action will run
# Workflow begins with push or PR events
# Focuses on the master branch only
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Create one single job
# This job performs all necessary checks
jobs:
  build:
    # Use the latest version of Ubuntu
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Performs all actions on different versions of Python
        python-version: ["3.11"]
        os: [ubuntu-latest]
    # Define the workflow steps
    steps:
    # Checkout the code of the repository
        - name: Check out Repository Code
          uses: actions/checkout@v3
          with:
            fetch-depth: 0
        # Setup Python for the current language version
        - name: Setup Python ${{ matrix.python-version }}
          if: always()
          uses: actions/setup-python@v4
          with:
            python-version: ${{ matrix.python-version }}
        # Install pip
        - name: Install Pip
          if: always()
          run: |
            pip install -U pip
            python -m pip install --user pipx
        # Run GatorGrader: see config/gatorgrade.yml
        - name: Run GatorGrader with GatorGrade
          run:  |
            pipx install gatorgrade
            gatorgrade --config config/gatorgrade.yml
